export type Frequency = 'monthly' | 'quarterly' | 'semi-annual' | 'annual';
export type Phase = 'construction' | 'operation';
export type InstrumentType = 'Equity' | 'Shareholder loan' | 'Senior debt' | 'Mezzanine debt' | 'Bridge loan' | 'ECA facility' | 'IFI / DFI facility' | 'VAT facility' | 'Working capital facility' | 'DSRA LC' | 'Refinancing debt' | 'Grant / subsidy';
export type RepaymentType = 'Straight-line principal' | 'Annuity' | 'Bullet' | 'Balloon' | 'Sculpted repayment' | 'Mini-perm' | 'Cash sweep' | 'Custom repayment profile';
export type Seniority = 'equity' | 'senior' | 'mezzanine' | 'subordinated';

export interface Period { index: number; label: string; start: string; end: string; phase: Phase; year: number; type: Frequency }
export interface TimelineAssumptions { frequency: Frequency; projectStart: string; constructionStart: string; cod: string; operationEnd: string; financingTenorMonths: number; gracePeriodMonths: number; repaymentPeriodMonths: number }
export interface OperatingAssumptions { revenue: number; operatingCost: number; maintenanceCapex: number; taxRate: number; workingCapitalMovement: number; depreciation: number; revenueEscalation?: number; costEscalation?: number }
export type DebtFundingMethod = 'Fixed amount' | '% of total debt' | '% of total uses' | 'Residual debt';
export type EquityFundingMethod = 'Fixed amount' | '% of total uses' | 'Residual funding / balancing item';
export interface FundingInstrument { id: string; name: string; type: InstrumentType; enabled: boolean; currency: string; commitment: number; availableFrom: string; availableUntil: string; fundingPriority: number; repaymentPriority: number; seniority: Seniority; interestType: 'fixed' | 'floating'; baseRate: number; margin: number; fixedRate: number; commitmentFee: number; upfrontFee: number; arrangementFee: number; agencyFee: number; undrawnFee: number; capitalizedInterest: boolean; accruedInterest: boolean; debtFundedFees: boolean; equityFundedFees: boolean; repaymentType: RepaymentType; tenorMonths: number; gracePeriodMonths: number; maturity: string; cashSweep: boolean; refinancingEligible: boolean; covenantPackage: string; distributionRestrictionRules: string[]; sizingMethod: string; targetDSCR: number; maxGearing: number; fundingMethod?: DebtFundingMethod | EquityFundingMethod; fundingPercentage?: number; fundingCap?: number; fundingFloor?: number; availableDuringConstruction?: boolean; includeInDebtSizing?: boolean; residualFunding?: boolean }
export interface ReserveAccount { id: string; name: string; type: string; method: string; months: number; fixedAmount: number; funding: 'cash funded' | 'debt funded' | 'LC-backed' }
export interface CovenantAssumptions { backwardDSCR: number; forwardDSCR: number; llcr: number; plcr: number; debtToEbitda: number; minimumCash: number; distributionLockup: boolean; cashTrap: boolean; defaultTrigger: boolean; equityCure: boolean; guaranteeRelease: { forwardDSCR: number; llcr: number; firstPrincipal: boolean; secondPrincipal: boolean; cod: boolean; noDefault: boolean; minimumOperatingPeriods: number } }
export interface Scenario { id: string; name: string; revenueMultiplier: number; opexMultiplier: number; capexMultiplier: number; rateShock: number }
export interface FundingStructure { targetGearing: number; equityResidual: boolean; tolerance: number; allowDebtAboveTarget?: boolean }
export interface ConstructionAssumptions { capex: number; contingency: number; costOverrunReserve: number; drawdownProfile?: 'straight-line' | 'front-loaded' | 'back-loaded' | 'custom placeholder' }
export interface ProjectModel { name: string; currency: string; timeline: TimelineAssumptions; operating: OperatingAssumptions; construction: ConstructionAssumptions; funding: FundingStructure; instruments: FundingInstrument[]; reserves: ReserveAccount[]; covenants: CovenantAssumptions; scenarios: Scenario[]; activeScenarioId: string }
export interface SolverLogEntry { iteration: number; variable: string; previous: number; next: number; delta: number; note: string; baseCapex?: number; financingCosts?: number; totalUses?: number; targetDebt?: number; equityFunding?: number; sourcesUsesDifference?: number; debtAllocation?: Record<string, number> }
export interface SolverResult { status: 'not run' | 'converged' | 'failed'; iterations: number; tolerance: number; finalDelta: number; variables: string[]; bindingConstraint?: string; failureReason?: string; warnings: string[]; log: SolverLogEntry[] }
export interface DebtSchedule { instrumentId: string; name: string; type: InstrumentType; seniority: Seniority; openingBalance: number[]; drawdown: number[]; interest: number[]; capitalizedInterest: number[]; fees: number[]; principal: number[]; cashSweep: number[]; closingBalance: number[] }
export interface ReserveSchedule { target: number[]; openingBalance: number[]; topUp: number[]; release: number[]; lcSupport: number[]; closingBalance: number[] }
export interface CovenantSummary { backwardDSCR: number[]; forwardDSCR: number[]; llcr: number[]; plcr: number[]; distributionLocked: boolean[]; cashTrap: boolean[]; defaultTrigger: boolean[] }
export interface DashboardMetrics { totalSources: number; totalUses: number; totalDebt: number; equityRequirement: number; idc: number; fees: number; dsra: number; minDSCR: number; avgDSCR: number; llcr: number; plcr: number; projectIrr: number; equityIrr: number; balanceSheetBalanced: boolean }
export interface ValidationMessage { severity: 'error' | 'warning'; message: string }
export interface SourcesUsesLine { section: 'Uses' | 'Sources' | 'Check'; label: string; amount: number }
export interface FundingSummary { baseCapex: number; financingCosts: number; totalUses: number; totalSources: number; targetDebt: number; equityFunding: number; grants: number; sourcesUsesDifference: number; balanced: boolean; debtAllocation: Record<string, number>; usesBreakdown: Record<string, number>; sourcesBreakdown: Record<string, number> }
export interface ModelResults { periods: Period[]; revenue: number[]; operatingCosts: number[]; ebitda: number[]; cfads: number[]; constructionDraw: number[]; debtDraws: number[]; fees: number[]; idc: number[]; principal: number[]; interest: number[]; closingDebt: number[]; dsra: number[]; distributions: number[]; closingCash: number[]; dscr: number[]; llcr: number; plcr: number; projectIrr: number; equityIrr: number; sourcesUses: SourcesUsesLine[]; fundingSummary: FundingSummary; incomeStatement: Record<string, number[]>; balanceSheet: Record<string, number[]>; cashFlowStatement: Record<string, number[]>; waterfall: Record<string, number[]>; debtSchedules: DebtSchedule[]; reserveSchedule: ReserveSchedule; covenants: CovenantSummary; solver: SolverResult; validation: ValidationMessage[]; warnings: string[]; balanceCheck: number[]; dashboard: DashboardMetrics; audit: string[] }
