export type Frequency='monthly'|'quarterly'|'semi-annual'|'annual';
export type Phase='construction'|'operation';
export type InstrumentType='Equity'|'Shareholder loan'|'Senior debt'|'Mezzanine debt'|'Bridge loan'|'ECA facility'|'IFI / DFI facility'|'VAT facility'|'Working capital facility'|'DSRA LC'|'Refinancing debt'|'Grant / subsidy';
export type RepaymentType='Straight-line principal'|'Annuity'|'Bullet'|'Balloon'|'Sculpted repayment'|'Mini-perm'|'Cash sweep'|'Custom repayment profile';
export interface Period{index:number;label:string;start:string;end:string;phase:Phase;year:number}
export interface TimelineAssumptions{frequency:Frequency;projectStart:string;constructionStart:string;cod:string;operationEnd:string;financingTenorMonths:number;gracePeriodMonths:number;repaymentPeriodMonths:number}
export interface OperatingAssumptions{revenue:number;operatingCost:number;maintenanceCapex:number;taxRate:number;workingCapitalMovement:number;depreciation:number}
export interface FundingInstrument{id:string;name:string;type:InstrumentType;enabled:boolean;currency:string;commitment:number;availableFrom:string;availableUntil:string;fundingPriority:number;repaymentPriority:number;seniority:'equity'|'senior'|'mezzanine'|'subordinated';interestType:'fixed'|'floating';baseRate:number;margin:number;fixedRate:number;commitmentFee:number;upfrontFee:number;arrangementFee:number;agencyFee:number;undrawnFee:number;capitalizedInterest:boolean;accruedInterest:boolean;debtFundedFees:boolean;equityFundedFees:boolean;repaymentType:RepaymentType;tenorMonths:number;gracePeriodMonths:number;maturity:string;cashSweep:boolean;refinancingEligible:boolean;covenantPackage:string;distributionRestrictionRules:string[];sizingMethod:string;targetDSCR:number;maxGearing:number}
export interface ReserveAccount{id:string;name:string;type:string;method:string;months:number;fixedAmount:number;funding:'cash funded'|'debt funded'|'LC-backed'}
export interface CovenantAssumptions{backwardDSCR:number;forwardDSCR:number;llcr:number;plcr:number;debtToEbitda:number;minimumCash:number;distributionLockup:boolean;cashTrap:boolean;defaultTrigger:boolean;equityCure:boolean;guaranteeRelease:{forwardDSCR:number;llcr:number;firstPrincipal:boolean;secondPrincipal:boolean;cod:boolean;noDefault:boolean;minimumOperatingPeriods:number}}
export interface Scenario{id:string;name:string;revenueMultiplier:number;opexMultiplier:number;capexMultiplier:number;rateShock:number}
export interface ProjectModel{name:string;currency:string;timeline:TimelineAssumptions;operating:OperatingAssumptions;construction:{capex:number;contingency:number;costOverrunReserve:number;vatBridge:number};instruments:FundingInstrument[];reserves:ReserveAccount[];covenants:CovenantAssumptions;scenarios:Scenario[];activeScenarioId:string}
export interface SolverLogEntry{iteration:number;variable:string;previous:number;next:number;delta:number;note:string}
export interface SolverResult{status:'not run'|'converged'|'failed';iterations:number;tolerance:number;finalDelta:number;variables:string[];bindingConstraint?:string;failureReason?:string;log:SolverLogEntry[]}
export interface ModelResults{periods:Period[];revenue:number[];operatingCosts:number[];ebitda:number[];cfads:number[];debtDraws:number[];fees:number[];idc:number[];principal:number[];interest:number[];closingDebt:number[];dsra:number[];distributions:number[];closingCash:number[];dscr:number[];llcr:number;plcr:number;projectIrr:number;equityIrr:number;sourcesUses:{source:string;amount:number}[];incomeStatement:Record<string,number[]>;balanceSheet:Record<string,number[]>;cashFlowStatement:Record<string,number[]>;solver:SolverResult;warnings:string[];balanceCheck:number[]}
